version: '3'
services:
  golang-instance:
    image: "rinha-developerarthur-golang"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: on-failure
    networks:
      - nginx_net

  golang-instance-2:
    image: "rinha-developerarthur-golang"
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - nginx_net

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - nginx_net

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - nginx_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - nginx_net

  nginx:
    image: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - golang-instance
      - golang-instance-2
    networks:
      - nginx_net

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "arthur@tatay.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      - nginx_net

networks:
  nginx_net: