version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

#  pgadmin-compose:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "arthur@tatay.com"
#      PGADMIN_DEFAULT_PASSWORD: "123456"
#    ports:
#      - "54321:80"
#    depends_on:
#      - postgres
#    volumes:
#      - ./database/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
#      - ./database/pgpass:/pgpass # passwords for the connections in this file

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"