version: '3'
services:
  golang-instance:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - nginx_net

  golang-instance-2:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - nginx_net

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=30'
    networks:
      - nginx_net

  nginx:
    image: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - golang-instance
      - golang-instance-2
    networks:
      - nginx_net

networks:
  nginx_net: