version: '3'
services:
  golang-instance:
    image: "rinha-developerarthur-golang"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    restart: on-failure
    networks:
      - nginx_net

  golang-instance-2:
    image: "rinha-developerarthur-golang"
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - nginx_net

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=30'
    networks:
      - nginx_net

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - nginx_net

  nginx:
    image: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - golang-instance
      - golang-instance-2
    networks:
      - nginx_net

networks:
  nginx_net: