version: '3'
services:
  golang-instance:
    image: "rinha-developerarthur-golang"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - rinha-network

  golang-instance-2:
    image: "rinha-developerarthur-golang"
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    networks:
      - rinha-network

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - rinha-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - rinha-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rinha-network

networks:
  rinha-network: