Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 3072
        vb.cpus = 2
    end

    config.vm.network "private_network", type: "dhcp"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        git clone https://github.com/DeveloperArthur/rinha-de-backend-2023.git
        cd rinha-de-backend-2023
        docker build -t rinha-developerarthur-golang .
        mkdir app/postgres-data
        sh stress-test.sh
    SHELL
end