Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 3072
        vb.cpus = 2
    end

    config.vm.network "private_network", type: "dhcp"

    config.vm.provision "shell", inline: <<-SHELL
        echo "Atualizando pacotes..."    
        apt-get update

        echo "Instalando pré-requisitos..."
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose
        sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y scala

        echo "Clonando o repositório..."
        git clone https://github.com/DeveloperArthur/rinha-de-backend-2023.git
        cd rinha-de-backend-2023/app
        mkdir postgres-data

        echo "Executando o script de teste de estresse..."
        cd ..
        bash stress-test.sh
    SHELL
end